# Generated by Django 4.0.10 on 2023-02-28 23:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('img', models.ImageField(upload_to='D:\\Github\\Fast-Eyes\\project\\media/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
