# Generated by Django 4.0.10 on 2023-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='incorrect',
            field=models.IntegerField(null=True),
        ),
    ]
