# Generated by Django 4.0.10 on 2023-03-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='D:\\Github\\Fast-Eyes\\project\\media'),
        ),
    ]
