# Generated by Django 4.0.10 on 2023-04-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
