# Generated by Django 4.0.10 on 2023-03-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_image_correct_alter_image_incorrect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='correct',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='incorrect',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
