version: '3.11'

services:
  db:
    image: postgres
    environment:
      - POSTGRESS_DB = postgres
      - POSTGRESS_USER = postgres
      - POSTGRESS_PASSWORD = Zx41pl//
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
