# Generated by Django 4.0.10 on 2023-02-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_age_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ailments',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
