# Generated by Django 4.0.10 on 2023-02-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_ailments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ailments',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
